import { source } from './schema.js';

export const SOURCES = Object.freeze([
  source('bls-gso-2025','BLS Greensboro-High Point Occupational Employment and Wages, May 2025','https://www.bls.gov/regions/southeast/news-release/occupationalemploymentandwages_greensboro.htm','2025-05'),
  source('bls-ws-2025','BLS Winston-Salem Occupational Employment and Wages, May 2025','https://www.bls.gov/regions/southeast/news-release/occupationalemploymentandwages_winston.htm','2025-05'),
  source('nc-proj-2024-34','NC Commerce 2024-2034 Regional Occupational Trends','https://www.commerce.nc.gov/data-tools-reports/labor-market-data-tools/employment-projections/north-carolina-employment-projections-2024-2034-regional-occupational-trends','2026-08'),
  source('nc-proj-state-2024-34','NC Commerce 2024-2034 Statewide Employment Projections','https://www.commerce.nc.gov/data-tools-reports/labor-market-data-tools/employment-projections/north-carolina-employment-projections-2024-2034-statewide-projections','2026-08'),
  source('nc-oes-d4','NC Commerce D4 Occupational Employment and Wage Statistics','https://d4.nccommerce.com/OESSelection.aspx','2026-08'),
  source('bls-ee','BLS Occupational Outlook Handbook - Electrical and Electronics Engineers','https://www.bls.gov/ooh/architecture-and-engineering/electrical-and-electronics-engineers.htm','2026-08'),
  source('bls-ie','BLS Occupational Outlook Handbook - Industrial Engineers','https://www.bls.gov/ooh/architecture-and-engineering/industrial-engineers.htm','2026-08'),
  source('bls-aircraft','BLS Occupational Outlook Handbook - Aircraft and Avionics Mechanics and Technicians','https://www.bls.gov/ooh/installation-maintenance-and-repair/aircraft-and-avionics-equipment-mechanics-and-technicians.htm','2026-08'),
  source('bls-industrial-maint','BLS Occupational Outlook Handbook - Industrial Machinery Mechanics, Maintenance Workers, and Millwrights','https://www.bls.gov/ooh/installation-maintenance-and-repair/industrial-machinery-mechanics-and-maintenance-workers-and-millwrights.htm','2026-08'),
  source('bls-electrician','BLS Occupational Outlook Handbook - Electricians','https://www.bls.gov/ooh/construction-and-extraction/electricians.htm','2026-08'),
  source('bls-hvac','BLS Occupational Outlook Handbook - HVACR Mechanics and Installers','https://www.bls.gov/ooh/installation-maintenance-and-repair/heating-air-conditioning-and-refrigeration-mechanics-and-installers.htm','2026-08'),
  source('bls-software','BLS Occupational Outlook Handbook - Software Developers, QA Analysts, and Testers','https://www.bls.gov/ooh/computer-and-information-technology/software-developers.htm','2026-08'),
  source('bls-infosec','BLS Occupational Outlook Handbook - Information Security Analysts','https://www.bls.gov/ooh/computer-and-information-technology/information-security-analysts.htm','2026-08'),
  source('bls-systems','BLS Occupational Outlook Handbook - Computer Systems Analysts','https://www.bls.gov/ooh/computer-and-information-technology/computer-systems-analysts.htm','2026-08'),
  source('bls-accounting','BLS Occupational Outlook Handbook - Accountants and Auditors','https://www.bls.gov/ooh/business-and-financial/accountants-and-auditors.htm','2026-08'),
  source('bls-logistics','BLS Occupational Outlook Handbook - Logisticians','https://www.bls.gov/ooh/business-and-financial/logisticians.htm','2026-08'),
  source('bls-lab','BLS Occupational Outlook Handbook - Clinical Laboratory Technologists and Technicians','https://www.bls.gov/ooh/healthcare/clinical-laboratory-technologists-and-technicians.htm','2026-08'),
  source('bls-hit','BLS Occupational Outlook Handbook - Health Information Technologists and Medical Registrars','https://www.bls.gov/ooh/healthcare/health-information-technologists-and-medical-registrars.htm','2026-08'),
  source('bls-med-equipment','BLS Occupational Outlook Handbook - Medical Equipment Repairers','https://www.bls.gov/ooh/installation-maintenance-and-repair/medical-equipment-repairers.htm','2026-08'),
  source('bls-rn','BLS Occupational Outlook Handbook - Registered Nurses','https://www.bls.gov/ooh/healthcare/registered-nurses.htm','2026-08'),
  source('bls-police','BLS Occupational Outlook Handbook - Police and Detectives','https://www.bls.gov/ooh/protective-service/police-and-detectives.htm','2026-08'),
  source('bls-911','BLS Occupational Outlook Handbook - Public Safety Telecommunicators','https://www.bls.gov/ooh/office-and-administrative-support/public-safety-telecommunicators.htm','2026-08'),
  source('bls-truck','BLS Occupational Outlook Handbook - Heavy and Tractor-trailer Truck Drivers','https://www.bls.gov/ooh/transportation-and-material-moving/heavy-and-tractor-trailer-truck-drivers.htm','2026-08'),

  source('gtcc-programs','GTCC Academic Programs','https://gtcc.edu/academics/academic-programs/index.php','2026-08'),
  source('gtcc-ai-2026','GTCC 2026 AI and Digital Media Program Expansion','https://www.gtcc.edu/about/news-and-events/2026/03/gtcc-expands-academic-offerings-with-ai-digital-media-programs.php','2026-03'),
  source('gtcc-aviation','GTCC Aviation Systems Technology','https://www.gtcc.edu/academics/academic-programs/programs/manufacturing-transportation-construction/aviation-systems-technology.php','2026-08'),
  source('gtcc-mechatronics','GTCC Mechatronics Engineering Technology','https://gtcc.edu/academics/academic-programs/programs/STEM/mechatronics-engineering-technology.php','2026-08'),
  source('gtcc-fame','GTCC NC FAME','https://www.gtcc.edu/gtccfame/index.php','2026-08'),
  source('gtcc-blet','GTCC Basic Law Enforcement Training (BLET)','https://www.gtcc.edu/academics/academic-programs/programs/public-safety/basic-law-enforcement-training.php','2026-08'),
  source('forsyth-catalog','Forsyth Tech 2026-27 Programs Offered','https://catalog.forsythtech.edu/2627/program','2026-08'),
  source('davidsondavie-programs','Davidson-Davie Community College Academic Programs','https://www.davidsondavie.edu/academic-programs-cip-code/','2026-08'),
  source('randolph-programs','Randolph Community College College Majors','https://www.randolph.edu/academics/college-majors/','2026-08'),
  source('randolph-industrial','Randolph CC Industrial Systems Technology','https://www.randolph.edu/academics/college-majors/industrial-systems-technology/index.aspx','2026-08'),
  source('alamance-programs','Alamance Community College Programs','https://www.alamancecc.edu/programs/','2026-08'),
  source('rockingham-programs','Rockingham Community College Programs','https://www.rockinghamcc.edu/programs/','2026-08'),
  source('surry-programs','Surry Community College Programs','https://surry.edu/areas-of-study/all-programs','2026-08'),
  source('wake-tech-programs','Wake Tech Academic Programs','https://www.waketech.edu/programs-courses','2026-08'),
  source('durham-tech-programs','Durham Tech Programs','https://www.durhamtech.edu/programs-courses','2026-08'),
  source('gap','Guilford Apprenticeship Partners','https://gapnc.org/','2026-08'),

  source('ncat-majors','NC A&T Majors, Minors and Programs','https://ncat.edu/academics/majors-minors-and-programs/','2026-08'),
  source('uncg-programs','UNCG 2026-27 Programs A-Z','https://www.catalog.uncg.edu/programs/a-z/','2026-08'),
  source('uncg-isscm','UNCG Information Systems & Supply Chain Management','https://bryan.uncg.edu/programs/undergraduate-programs/information-systems-and-supply-chain-management-major/','2026-08'),
  source('uncg-accounting','UNCG Accounting Major','https://bryan.uncg.edu/programs/undergraduate-programs/accounting-major/','2026-08'),
  source('wssu-programs','Winston-Salem State University Undergraduate Programs','https://wssu.edu/admissions/programs/index.html','2026-08'),
  source('charlotte-programs','UNC Charlotte Undergraduate Programs','https://academics.charlotte.edu/undergraduate-programs/','2026-08'),
  source('elon-programs','Elon University Majors, Minors and Programs','https://www.elon.edu/u/academics/majors-minors-programs/','2026-08'),
  source('guilford-programs','Guilford College Academic Programs','https://catalog.guilford.edu/catalog/academic-departments-majors/','2026-08'),
  source('hpu-programs','High Point University Majors and Minors','https://www.highpoint.edu/academics/majors-minors/','2026-08'),
  source('wake-forest-programs','Wake Forest Undergraduate Bulletin','https://bulletin.wfu.edu/undergraduate/','2026-08'),
  source('ncstate-programs','NC State University 2026-27 Undergraduate Catalog','https://catalog.ncsu.edu/undergraduate/','2026-08'),

  source('nces-cip-soc','NCES 2020 CIP-SOC Crosswalk','https://nces.ed.gov/ipeds/cipcode/Files/IES2020_CIP_SOC_Crosswalk_508C.pdf','2020'),
  source('pti-aerospace','Piedmont Triad Airport Authority - Aerospace','https://flyfrompti.com/building-the-future-of-aerospace/','2026-08'),
  source('toyota-nc','Toyota Battery Manufacturing North Carolina','https://pressroom.toyota.com/facility/toyota-battery-manufacturing-north-carolina/','2026-08'),
  source('jetzero-nc','NC Commerce - JetZero Greensboro project','https://www.commerce.nc.gov/news/press-releases/2026/06/15/governor-stein-celebrates-jetzero-groundbreaking-launch-greensboro-airplane-makers-14500-job-project','2026-06'),

  source('dfas-2026','DFAS 2026 Enlisted Basic Pay','https://www.dfas.mil/MilitaryMembers/payentitlements/Pay-Tables/Basic-Pay/EM/','2026'),
  source('va-gi-bill','VA Post-9/11 GI Bill Rates','https://www.va.gov/education/benefit-rates/post-9-11-gi-bill-rates/','2026-27'),
  source('nc-guard-ta','NC National Guard Tuition Assistance Program','https://ng.nc.gov/north-carolina-tuition-assistance-program-nctap','2026-08'),
  source('military-onesource-careers','Military OneSource - Military Jobs, Opportunities & Resources','https://www.militaryonesource.mil/resources/millife-guides/military-career/','2026-08'),
  source('goarmy-careers','U.S. Army Careers and Jobs','https://www.goarmy.com/careers-and-jobs','2026-08'),
  source('goarmy-35p','U.S. Army - 35P Signals Intelligence Voice Interceptor','https://www.goarmy.com/careers-and-jobs/signal-intelligence/languages-code/35p-signals-intelligence-voice-interceptor','2026-08'),
  source('airforce-careers','U.S. Air Force Career Finder','https://www.airforce.com/careers/career-finder','2026-08'),
  source('airforce-cyber-intel','U.S. Air Force Cyber and Intelligence Careers','https://www.airforce.com/careers/intelligence','2026-08'),
  source('airforce-law-order','U.S. Air Force Law and Order Careers','https://www.airforce.com/careers/law-and-order','2026-08'),
  source('airforce-cyber-systems','U.S. Air Force - Enlisted Cyber System Operations','https://www.airforce.com/careers/intelligence/cyber-system-operations','2026-08'),
  source('navy-careers','U.S. Navy Careers','https://www.navy.com/careers-benefits/careers','2026-08'),
  source('navy-construction','U.S. Navy Construction Careers','https://www.navy.com/careers-benefits/careers/construction','2026-08'),
  source('spaceforce-careers','U.S. Space Force Careers','https://www.spaceforce.com/careers','2026-08'),
  source('coastguard-careers','U.S. Coast Guard Enlisted Careers','https://gocoastguard.com/careers/enlisted','2026-08'),
  source('marines-roles','U.S. Marine Corps Roles and Military Occupational Specialties','https://www.marines.com/about-the-marine-corps/roles/military-occupational-specialty.html','2026-08'),
  source('americorps-nccc','AmeriCorps NCCC','https://www.americorps.gov/serve/americorps/americorps-nccc','2026-08')
]);

export const SOURCE_BY_ID = Object.freeze(Object.fromEntries(SOURCES.map(item => [item.id, item])));
