export const DIMENSIONS = {
  earlyEarnings: 'Early earnings',
  incomeCeiling: 'Income ceiling',
  affordability: 'Low education cost',
  schoolTolerance: 'School tolerance',
  patientContact: 'Patient contact',
  handsOnTech: 'Hands-on technology',
  scienceTolerance: 'Science intensity',
  deskPreference: 'Desk / software work',
  schedulePredictability: 'Schedule predictability',
  highStakesTolerance: 'High-stakes responsibility',
  physicalTolerance: 'Physical work tolerance',
  jobStability: 'Job stability',
  geographicFlexibility: 'Geographic flexibility',
  careerLadder: 'Advancement / pivot options'
};

const baseAttrs = {
  earlyEarnings:50,incomeCeiling:50,affordability:50,schoolTolerance:50,
  patientContact:50,handsOnTech:50,scienceTolerance:50,deskPreference:50,
  schedulePredictability:50,highStakesTolerance:50,physicalTolerance:50,
  jobStability:50,geographicFlexibility:50,careerLadder:50
};
const A = overrides => ({...baseAttrs,...overrides});
const F = (trainingYears,tuition,startSalary,targetSalary,growth=.03,kind='standard') => ({trainingYears,tuition,startSalary,targetSalary,growth,kind});

export const CAREERS = [
  {id:'sonography',name:'Diagnostic Medical Sonography',tags:['2-year path','imaging','patients'],blurb:'Real-time diagnostic imaging, anatomy and patient care with unusually fast entry into a well-paid clinical profession.',caveat:'Physical repetition, close patient contact and competitive program admissions can matter more than the degree title.',attrs:A({earlyEarnings:94,incomeCeiling:62,affordability:94,schoolTolerance:22,patientContact:82,handsOnTech:88,scienceTolerance:67,deskPreference:24,schedulePredictability:62,highStakesTolerance:55,physicalTolerance:78,jobStability:82,geographicFlexibility:78,careerLadder:58}),finance:F(2,14000,76000,97240,.025)},
  {id:'nuclear-medicine',name:'Nuclear Medicine Technology',tags:['2-year path','PET/SPECT','radiopharmacy'],blurb:'Imaging technology, radioactive tracers and physiology in a small, specialized clinical field.',caveat:'Excellent specialization, but fewer employers and positions than broad imaging fields.',attrs:A({earlyEarnings:91,incomeCeiling:66,affordability:90,schoolTolerance:24,patientContact:68,handsOnTech:94,scienceTolerance:82,deskPreference:25,schedulePredictability:65,highStakesTolerance:62,physicalTolerance:58,jobStability:66,geographicFlexibility:48,careerLadder:52}),finance:F(2,18000,72000,105160,.025)},
  {id:'radiation-therapy',name:'Radiation Therapy',tags:['2–3 years','oncology','linear accelerator'],blurb:'Deliver precision radiation treatments using high-end equipment while working directly with cancer patients.',caveat:'Emotionally serious work and a smaller labor market than general imaging.',attrs:A({earlyEarnings:84,incomeCeiling:74,affordability:82,schoolTolerance:34,patientContact:76,handsOnTech:92,scienceTolerance:76,deskPreference:22,schedulePredictability:77,highStakesTolerance:75,physicalTolerance:54,jobStability:74,geographicFlexibility:55,careerLadder:59}),finance:F(3,26000,76000,114990,.026)},
  {id:'mri',name:'MRI Technologist',tags:['2–3 years','imaging','scanner technology'],blurb:'Operate advanced magnetic-resonance imaging systems with substantial patient interaction and strong portability.',caveat:'Often reached through radiography or an imaging pathway rather than a single universal direct-entry route.',attrs:A({earlyEarnings:83,incomeCeiling:60,affordability:84,schoolTolerance:30,patientContact:72,handsOnTech:90,scienceTolerance:62,deskPreference:22,schedulePredictability:60,highStakesTolerance:54,physicalTolerance:66,jobStability:82,geographicFlexibility:84,careerLadder:62}),finance:F(3,24000,69000,96120,.025)},
  {id:'respiratory',name:'Respiratory Therapy',tags:['2-year path','ICU','ventilators'],blurb:'Manage ventilators, airways and respiratory treatment across hospitals, ICUs and emergency settings.',caveat:'Strong employability comes with shift work, bedside care and exposure to very sick patients.',attrs:A({earlyEarnings:91,incomeCeiling:55,affordability:92,schoolTolerance:22,patientContact:92,handsOnTech:76,scienceTolerance:67,deskPreference:12,schedulePredictability:32,highStakesTolerance:80,physicalTolerance:72,jobStability:91,geographicFlexibility:90,careerLadder:54}),finance:F(2,14000,65000,87300,.024)},
  {id:'dental-hygiene',name:'Dental Hygiene',tags:['2–3 years','clinical','predictable hours'],blurb:'Hands-on preventive oral care with strong hourly pay and often more predictable schedules than hospital work.',caveat:'Repetitive ergonomics and a narrower career ladder can become limiting over time.',attrs:A({earlyEarnings:88,incomeCeiling:55,affordability:86,schoolTolerance:28,patientContact:90,handsOnTech:54,scienceTolerance:55,deskPreference:10,schedulePredictability:90,highStakesTolerance:42,physicalTolerance:80,jobStability:80,geographicFlexibility:88,careerLadder:38}),finance:F(3,22000,70000,94320,.022)},
  {id:'rn',name:'Registered Nursing',tags:['2–4 years','broad demand','clinical'],blurb:'A massive, portable clinical labor market with many specialties and a strong ladder into advanced practice.',caveat:'The job can be physically and emotionally demanding, and bedside schedules are often rough early on.',attrs:A({earlyEarnings:86,incomeCeiling:67,affordability:78,schoolTolerance:35,patientContact:98,handsOnTech:56,scienceTolerance:66,deskPreference:12,schedulePredictability:24,highStakesTolerance:82,physicalTolerance:86,jobStability:97,geographicFlexibility:98,careerLadder:92}),finance:F(2,16000,68000,101420,.028)},
  {id:'crna',name:'Nurse Anesthetist (CRNA)',tags:['advanced practice','anesthesia','$200K+'],blurb:'High-stakes anesthesia practice with exceptional compensation and national portability after nursing and ICU experience.',caveat:'The path requires RN licensure, critical-care experience and a three-year doctoral anesthesia program.',attrs:A({earlyEarnings:30,incomeCeiling:99,affordability:62,schoolTolerance:96,patientContact:82,handsOnTech:86,scienceTolerance:96,deskPreference:12,schedulePredictability:38,highStakesTolerance:99,physicalTolerance:48,jobStability:96,geographicFlexibility:97,careerLadder:86}),finance:F(7,73000,220000,248320,.028,'crna')},
  {id:'caa',name:'Certified Anesthesiologist Assistant',tags:['graduate school','anesthesia','$200K+'],blurb:'Anesthesia care-team practice with extraordinary starting compensation and a shorter route than CRNA for non-nurses.',caveat:'Graduate tuition can be very high and practice is limited to states that authorize CAAs.',attrs:A({earlyEarnings:43,incomeCeiling:99,affordability:14,schoolTolerance:88,patientContact:78,handsOnTech:88,scienceTolerance:96,deskPreference:10,schedulePredictability:40,highStakesTolerance:99,physicalTolerance:42,jobStability:90,geographicFlexibility:39,careerLadder:72}),finance:F(6,165000,215000,255000,.027)},
  {id:'perfusion',name:'Cardiovascular Perfusion',tags:['master’s','OR technology','heart-lung systems'],blurb:'Operate extracorporeal circulation and life-support technology during cardiac surgery.',caveat:'Tiny profession, concentrated employers and call schedules trade portability for specialization and pay.',attrs:A({earlyEarnings:46,incomeCeiling:88,affordability:48,schoolTolerance:84,patientContact:42,handsOnTech:99,scienceTolerance:95,deskPreference:8,schedulePredictability:18,highStakesTolerance:100,physicalTolerance:45,jobStability:82,geographicFlexibility:28,careerLadder:54}),finance:F(5,85000,125000,170000,.027)},
  {id:'pa',name:'Physician Assistant',tags:['master’s','diagnosis','broad medicine'],blurb:'Practice medicine across many specialties with high compensation and strong geographic portability.',caveat:'Requires a bachelor’s, prerequisite sciences, patient-care hours and competitive graduate admission.',attrs:A({earlyEarnings:38,incomeCeiling:88,affordability:38,schoolTolerance:90,patientContact:94,handsOnTech:48,scienceTolerance:92,deskPreference:30,schedulePredictability:50,highStakesTolerance:88,physicalTolerance:48,jobStability:94,geographicFlexibility:95,careerLadder:84}),finance:F(6,105000,115000,141280,.028)},
  {id:'dosimetry',name:'Medical Dosimetry',tags:['oncology','treatment planning','high pay'],blurb:'Use imaging, radiation physics and treatment-planning software to design cancer radiation doses.',caveat:'Small field with specialized education; it is more computer/physics heavy and less direct-entry than sonography.',attrs:A({earlyEarnings:45,incomeCeiling:90,affordability:48,schoolTolerance:78,patientContact:35,handsOnTech:79,scienceTolerance:96,deskPreference:82,schedulePredictability:84,highStakesTolerance:86,physicalTolerance:22,jobStability:80,geographicFlexibility:45,careerLadder:58}),finance:F(5,72000,105000,148500,.027)},
  {id:'biomed-equipment',name:'Biomedical Equipment Technician',tags:['2-year path','hardware','hospital technology'],blurb:'Install, maintain and troubleshoot medical devices and hospital equipment without becoming a clinician.',caveat:'Compensation is usually below the strongest licensed imaging professions, but the tech fit and low-cost entry are excellent.',attrs:A({earlyEarnings:88,incomeCeiling:48,affordability:94,schoolTolerance:20,patientContact:20,handsOnTech:98,scienceTolerance:58,deskPreference:28,schedulePredictability:67,highStakesTolerance:62,physicalTolerance:67,jobStability:82,geographicFlexibility:84,careerLadder:68}),finance:F(2,14000,52000,76000,.03)},
  {id:'health-informatics',name:'Healthcare / Imaging Informatics',tags:['bachelor’s','systems','healthcare tech'],blurb:'Work where clinical workflows, imaging systems, data, integrations and enterprise technology intersect.',caveat:'The strongest roles often reward prior clinical or technical experience, so the path can be less direct than a licensed clinical credential.',attrs:A({earlyEarnings:60,incomeCeiling:78,affordability:68,schoolTolerance:55,patientContact:18,handsOnTech:62,scienceTolerance:38,deskPreference:90,schedulePredictability:82,highStakesTolerance:48,physicalTolerance:12,jobStability:82,geographicFlexibility:84,careerLadder:88}),finance:F(4,30000,65000,115000,.035)},
  {id:'information-systems',name:'Information Systems / Business Technology',tags:['bachelor’s','business + tech','broad'],blurb:'Translate business needs into systems, data, projects and technology decisions across many industries.',caveat:'Broad optionality comes with a less guaranteed first-job outcome than licensed healthcare careers.',attrs:A({earlyEarnings:63,incomeCeiling:78,affordability:68,schoolTolerance:52,patientContact:5,handsOnTech:45,scienceTolerance:28,deskPreference:96,schedulePredictability:83,highStakesTolerance:38,physicalTolerance:5,jobStability:70,geographicFlexibility:95,careerLadder:93}),finance:F(4,30000,62000,112000,.038)},
  {id:'cybersecurity',name:'Cybersecurity',tags:['bachelor’s-ish','technical','broad market'],blurb:'Protect systems, investigate risk and incidents, and build controls across a wide range of industries.',caveat:'Entry-level hiring is less automatic than the headlines suggest; internships, labs and specialization matter.',attrs:A({earlyEarnings:58,incomeCeiling:88,affordability:66,schoolTolerance:52,patientContact:0,handsOnTech:62,scienceTolerance:35,deskPreference:94,schedulePredictability:66,highStakesTolerance:67,physicalTolerance:2,jobStability:81,geographicFlexibility:97,careerLadder:95}),finance:F(4,30000,68000,132510,.04)},
  {id:'software',name:'Software Development',tags:['bachelor’s-ish','coding','high ceiling'],blurb:'Build and maintain software systems with a high compensation ceiling and broad industry reach.',caveat:'The market is cyclical and early-career competition can be intense; the work is heavily desk-based.',attrs:A({earlyEarnings:61,incomeCeiling:94,affordability:64,schoolTolerance:52,patientContact:0,handsOnTech:42,scienceTolerance:50,deskPreference:100,schedulePredictability:77,highStakesTolerance:42,physicalTolerance:0,jobStability:62,geographicFlexibility:98,careerLadder:96}),finance:F(4,30000,78000,148100,.04)},
  {id:'electrical-engineering',name:'Electrical Engineering',tags:['bachelor’s','math + physics','hardware'],blurb:'Design, test and troubleshoot electrical systems using mathematics, simulation and physical hardware.',caveat:'Strong career economics, but only if sustained math and physics work is genuinely tolerable.',attrs:A({earlyEarnings:62,incomeCeiling:86,affordability:64,schoolTolerance:62,patientContact:0,handsOnTech:82,scienceTolerance:98,deskPreference:67,schedulePredictability:83,highStakesTolerance:60,physicalTolerance:25,jobStability:82,geographicFlexibility:88,careerLadder:87}),finance:F(4,32000,76000,125100,.035)},
  {id:'accounting',name:'Accounting',tags:['bachelor’s','structured','portable'],blurb:'Structured financial work with a large labor market, clear credential ladder and broad industry portability.',caveat:'Busy seasons and repetitive desk work can be the price of predictability and portability.',attrs:A({earlyEarnings:62,incomeCeiling:70,affordability:68,schoolTolerance:52,patientContact:0,handsOnTech:18,scienceTolerance:20,deskPreference:98,schedulePredictability:71,highStakesTolerance:40,physicalTolerance:0,jobStability:88,geographicFlexibility:98,careerLadder:91}),finance:F(4,30000,60000,94750,.035)},
  {id:'actuary',name:'Actuarial Science',tags:['bachelor’s + exams','math','high ceiling'],blurb:'Quantify financial risk using probability, statistics and business judgment with a strong long-term salary curve.',caveat:'The exam pipeline is lengthy and the day-to-day work is heavily analytical and desk-based.',attrs:A({earlyEarnings:56,incomeCeiling:91,affordability:65,schoolTolerance:70,patientContact:0,handsOnTech:15,scienceTolerance:88,deskPreference:100,schedulePredictability:88,highStakesTolerance:53,physicalTolerance:0,jobStability:90,geographicFlexibility:89,careerLadder:93}),finance:F(4,32000,72000,141480,.04)},
  {id:'atc',name:'Air Traffic Controller',tags:['specialized training','high pay','no grad school'],blurb:'Manage aircraft separation and traffic flow in a highly structured, safety-critical federal career.',caveat:'Age limits, medical screening, federal hiring, shift work and intense concentration make this a very specific fit.',attrs:A({earlyEarnings:76,incomeCeiling:84,affordability:84,schoolTolerance:24,patientContact:0,handsOnTech:69,scienceTolerance:52,deskPreference:72,schedulePredictability:20,highStakesTolerance:100,physicalTolerance:5,jobStability:92,geographicFlexibility:42,careerLadder:62}),finance:F(3,18000,65000,144580,.03,'atc')}
];

const opt = (label,effects={}) => ({label,effects});
export const QUESTIONS = [
  {round:'Kill it',prompt:'You will work directly with patients most of the day.',context:'Touching, positioning, explaining, reassuring and dealing with people who may be sick or uncomfortable.',options:[opt('That is fine.',{patientContact:+18}),opt('Some patient contact is okay.',{patientContact:+8}),opt('I would rather keep it limited.',{patientContact:-12}),opt('Absolutely not.',{patientContact:-26})]},
  {round:'Kill it',prompt:'Your training includes anatomy, physiology and real science classes.',context:'Not impossible science. But you cannot bluff your way through it.',options:[opt('Good. I like science.',{scienceTolerance:+22}),opt('I can handle it for a payoff.',{scienceTolerance:+10}),opt('I would rather minimize it.',{scienceTolerance:-12}),opt('Hard no.',{scienceTolerance:-25})]},
  {round:'Kill it',prompt:'Your job is mostly sitting at a computer.',context:'Meetings, software, documentation and screen time are normal.',options:[opt('Perfectly fine.',{deskPreference:+20}),opt('Fine if the work is interesting.',{deskPreference:+10}),opt('I need to move around.',{deskPreference:-14,physicalTolerance:+8}),opt('That sounds miserable.',{deskPreference:-26,physicalTolerance:+10})]},
  {round:'Kill it',prompt:'The job can involve blood, needles, bodily fluids or seriously ill people.',context:'You do not have to love it, but you cannot freeze when it happens.',options:[opt('I can handle that.',{patientContact:+12,highStakesTolerance:+10}),opt('Probably.',{patientContact:+5}),opt('I would prefer to avoid it.',{patientContact:-13}),opt('No chance.',{patientContact:-24,highStakesTolerance:-8})]},
  {round:'Kill it',prompt:'You may be on your feet and using your body for much of the shift.',context:'Positioning equipment or patients, walking units, or working in clinical spaces.',options:[opt('I prefer that.',{physicalTolerance:+22,deskPreference:-8}),opt('Fine.',{physicalTolerance:+10}),opt('I prefer lighter physical work.',{physicalTolerance:-10,deskPreference:+5}),opt('I want a desk.',{physicalTolerance:-24,deskPreference:+12})]},
  {round:'Kill it',prompt:'A career requires graduate school before the big paycheck arrives.',context:'Assume the payoff is real, but you will be in school longer.',options:[opt('Fine for the right payoff.',{schoolTolerance:+22,incomeCeiling:+8}),opt('Maybe.',{schoolTolerance:+8}),opt('I strongly prefer a short path.',{schoolTolerance:-16,earlyEarnings:+10}),opt('No graduate school.',{schoolTolerance:-26,earlyEarnings:+14})]},
  {round:'Tradeoffs',prompt:'Choose the better deal.',context:'Same general fit. Different timing.',options:[opt('$80K around age 20 with almost no debt.',{earlyEarnings:+22,affordability:+16}),opt('$120K around age 23 with moderate schooling.',{earlyEarnings:+8,incomeCeiling:+9}),opt('$220K around age 25–26 after expensive training.',{incomeCeiling:+24,schoolTolerance:+16,affordability:-14,earlyEarnings:-10})]},
  {round:'Tradeoffs',prompt:'Choose the workweek.',context:'Assume compensation is already acceptable.',options:[opt('Three 12-hour shifts, including some weekends.',{schedulePredictability:-12,physicalTolerance:+5}),opt('Five predictable office days.',{schedulePredictability:+18,deskPreference:+12}),opt('Variable schedule, but highly technical work.',{handsOnTech:+18,schedulePredictability:-9})]},
  {round:'Tradeoffs',prompt:'Your employer offers a promotion to management.',context:'More meetings, people problems and accountability. Less hands-on work.',options:[opt('Yes. I want the ladder.',{careerLadder:+22,deskPreference:+5}),opt('Maybe eventually.',{careerLadder:+8}),opt('I would rather remain a highly paid specialist.',{careerLadder:-9,handsOnTech:+12}),opt('Please never make me manage people.',{careerLadder:-20})]},
  {round:'Tradeoffs',prompt:'Which kind of technology sounds better?',context:'There is no right answer.',options:[opt('Physical machines, scanners, instruments and hardware.',{handsOnTech:+24,deskPreference:-6}),opt('Software, systems, data and computers.',{deskPreference:+20,handsOnTech:+3}),opt('A mix of both.',{handsOnTech:+14,deskPreference:+8})]},
  {round:'Tradeoffs',prompt:'A specialized job pays more but has only a handful of employers in each city.',context:'Changing jobs might eventually mean moving.',options:[opt('Worth it for specialization and pay.',{geographicFlexibility:-16,incomeCeiling:+10}),opt('I could live with that.',{geographicFlexibility:-6}),opt('I want many local employers.',{geographicFlexibility:+18,jobStability:+5}),opt('Maximum portability matters a lot.',{geographicFlexibility:+25})]},
  {round:'Tradeoffs',prompt:'Which safety net matters more?',context:'Imagine the first plan does not work out.',options:[opt('A credential that lets me earn good money immediately.',{earlyEarnings:+15,affordability:+8,jobStability:+10}),opt('A broad degree that lets me pivot into many fields.',{careerLadder:+20,geographicFlexibility:+10}),opt('I care mostly about the best final career.',{incomeCeiling:+14,schoolTolerance:+8})]},
  {round:'Tuesday',prompt:'Most of your day is spent in a dim room using imaging equipment in real time.',context:'You work one-on-one with patients, position equipment, and look for anatomy while the patient is right there.',options:[opt('That sounds genuinely interesting.',{handsOnTech:+18,patientContact:+13,physicalTolerance:+8}),opt('I could see myself doing it.',{handsOnTech:+9,patientContact:+6}),opt('Meh.',{}),opt('No.',{handsOnTech:-7,patientContact:-10})]},
  {round:'Tuesday',prompt:'You administer tiny quantities of radioactive material and use PET/SPECT-style scanners to see how organs function.',context:'There is radiation safety, dose handling, imaging technology and patient care.',options:[opt('That is cool as hell.',{handsOnTech:+22,scienceTolerance:+16,patientContact:+5}),opt('Interesting enough.',{handsOnTech:+10,scienceTolerance:+7}),opt('Not especially.',{scienceTolerance:-4}),opt('Absolutely not.',{scienceTolerance:-12,handsOnTech:-7})]},
  {round:'Tuesday',prompt:'You are in an operating room and the patient’s circulation depends partly on the machine you are operating.',context:'You are calm, technical and responsible while everyone else is doing surgery.',options:[opt('That sounds incredible.',{handsOnTech:+22,highStakesTolerance:+24,scienceTolerance:+10}),opt('I could handle it.',{highStakesTolerance:+12,handsOnTech:+10}),opt('That is too much responsibility.',{highStakesTolerance:-16}),opt('Nightmare.',{highStakesTolerance:-26})]},
  {round:'Tuesday',prompt:'You monitor an unconscious patient, manage anesthesia equipment and medications, and react immediately when physiology changes.',context:'Very high consequence. Very high compensation.',options:[opt('That is exactly the kind of responsibility I want.',{highStakesTolerance:+24,scienceTolerance:+12,incomeCeiling:+8}),opt('I could grow into it.',{highStakesTolerance:+10,scienceTolerance:+6}),opt('The money is tempting; the work isn’t.',{incomeCeiling:+10,highStakesTolerance:-14}),opt('No chance.',{highStakesTolerance:-24})]},
  {round:'Tuesday',prompt:'You spend your day solving business-process problems with software, data, meetings and documentation.',context:'Usually climate-controlled. Usually a computer. Usually several stakeholders.',options:[opt('That sounds good.',{deskPreference:+20,careerLadder:+8}),opt('Fine if the projects are interesting.',{deskPreference:+9}),opt('I need something more tangible.',{deskPreference:-10,handsOnTech:+10}),opt('That sounds soul-killing.',{deskPreference:-22})]},
  {round:'Tuesday',prompt:'You design and troubleshoot electrical systems using math, physics, simulation tools and lab equipment.',context:'Less human care, more engineering problem solving.',options:[opt('Very appealing.',{scienceTolerance:+20,handsOnTech:+14,patientContact:-8}),opt('Maybe.',{scienceTolerance:+8,handsOnTech:+6}),opt('Too much math/physics.',{scienceTolerance:-16}),opt('Not interested.',{handsOnTech:-6})]},
  {round:'Tuesday',prompt:'You spend much of the day with spreadsheets, financial systems, controls, reconciliations and deadlines.',context:'The work is stable and portable. Busy seasons can be real.',options:[opt('I like structured business work.',{deskPreference:+18,schedulePredictability:+8}),opt('I could tolerate it.',{deskPreference:+7}),opt('Only for great money.',{incomeCeiling:+8}),opt('Nope.',{deskPreference:-12})]},
  {round:'Tuesday',prompt:'You troubleshoot medical devices and equipment instead of treating the patient.',context:'You still work around hospitals, but the machine is your primary customer.',options:[opt('That sounds excellent.',{handsOnTech:+24,patientContact:-16,scienceTolerance:+8}),opt('Pretty interesting.',{handsOnTech:+12,patientContact:-7}),opt('I would rather be clinical.',{patientContact:+12}),opt('Not my thing.',{handsOnTech:-10})]},
  {round:'Pressure',prompt:'You are on call tonight. At 2:15 AM your phone rings.',context:'The work is specialized and pays $140K–$170K.',options:[opt('Fine. That is part of the deal.',{schedulePredictability:-16,highStakesTolerance:+10,incomeCeiling:+5}),opt('Occasionally, sure.',{schedulePredictability:-6}),opt('I would resent it.',{schedulePredictability:+12}),opt('Dealbreaker.',{schedulePredictability:+24})]},
  {round:'Pressure',prompt:'Your job requires rotating weekends, holidays or nights.',context:'The schedule may improve with seniority, but it is not guaranteed.',options:[opt('Doesn’t bother me.',{schedulePredictability:-18}),opt('I can do it for several years.',{schedulePredictability:-8,careerLadder:+5}),opt('I strongly prefer normal hours.',{schedulePredictability:+16}),opt('No nights or weekends.',{schedulePredictability:+25})]},
  {round:'Pressure',prompt:'A small mistake could have immediate safety consequences.',context:'The profession trains you heavily, but the stakes are real.',options:[opt('That makes the work meaningful.',{highStakesTolerance:+22}),opt('I can handle responsibility.',{highStakesTolerance:+10}),opt('I prefer lower-stakes work.',{highStakesTolerance:-12}),opt('That would make me miserable.',{highStakesTolerance:-24})]},
  {round:'Pressure',prompt:'Your field has huge demand, but the work itself can be emotionally exhausting.',context:'You would rarely worry about finding employment.',options:[opt('Stability matters more.',{jobStability:+20,patientContact:+5}),opt('That trade is acceptable.',{jobStability:+10}),opt('Quality of life matters more.',{schedulePredictability:+8,patientContact:-7}),opt('No amount of demand fixes burnout.',{patientContact:-12,highStakesTolerance:-8})]},
  {round:'Pressure',prompt:'A recession hits and your employer starts cutting staff.',context:'How much does labor-market defensibility matter to you?',options:[opt('A lot. I want a credential they still need.',{jobStability:+24}),opt('It matters.',{jobStability:+12}),opt('I will accept more market risk for upside.',{jobStability:-8,incomeCeiling:+10}),opt('I mainly care about doing interesting work.',{jobStability:-12,handsOnTech:+5})]},
  {round:'Money',prompt:'Suppose you can live at home while you train.',context:'Your direct education cost could be extremely low.',options:[opt('Exploit that advantage aggressively.',{affordability:+22,earlyEarnings:+12}),opt('It matters, but fit matters more.',{affordability:+8}),opt('I would still pay more for a clearly better career.',{incomeCeiling:+8,affordability:-6})]},
  {round:'Money',prompt:'You graduate debt-free at 20 and can invest $15,000 a year immediately.',context:'Another path starts at 25 but pays twice as much.',options:[opt('I love the early compounding advantage.',{earlyEarnings:+22,affordability:+10}),opt('Depends how much more the later job pays.',{incomeCeiling:+8}),opt('I would gladly wait for the bigger career.',{incomeCeiling:+20,schoolTolerance:+12,earlyEarnings:-10})]},
  {round:'Money',prompt:'A graduate program costs $150K but the current job market pays around $225K+.',context:'Assume the job itself fits you.',options:[opt('The ROI can justify the debt.',{incomeCeiling:+20,affordability:-18,schoolTolerance:+10}),opt('Maybe, but I would hate the debt.',{incomeCeiling:+9,affordability:+10}),opt('No. I want a cheaper route.',{affordability:+24,schoolTolerance:-6})]},
  {round:'Money',prompt:'How much do you care about hitting $100K as quickly as possible?',context:'This is about timing, not eventual lifetime earnings.',options:[opt('A lot. Early money matters.',{earlyEarnings:+24}),opt('It is a strong preference.',{earlyEarnings:+13}),opt('Nice, but not decisive.',{earlyEarnings:+3}),opt('I care more about eventual fit and upside.',{earlyEarnings:-12,incomeCeiling:+8})]},
  {round:'Money',prompt:'Which outcome sounds worst?',context:'This question is deliberately mean.',options:[opt('Debt.',{affordability:+24}),opt('Low salary ceiling.',{incomeCeiling:+24}),opt('Being stuck in one field.',{careerLadder:+22,geographicFlexibility:+8}),opt('Years of school.',{schoolTolerance:-24,earlyEarnings:+10})]}
];

export const SOURCES = [
  ['BLS 2025 national wage table','https://www.bls.gov/news.release/ocwage.t01.htm'],
  ['BLS Diagnostic Medical Sonographers','https://www.bls.gov/ooh/healthcare/diagnostic-medical-sonographers.htm'],
  ['BLS Nuclear Medicine Technologists','https://www.bls.gov/ooh/healthcare/nuclear-medicine-technologists.htm'],
  ['BLS Air Traffic Controllers','https://www.bls.gov/ooh/transportation-and-material-moving/air-traffic-controllers.htm'],
  ['BLS Dental Hygienists','https://www.bls.gov/ooh/healthcare/dental-hygienists.htm'],
  ['UNC Health CAA posting (2026)','https://jobs.unchealthcare.org/jobs/14978728-anesthesiology-assistant-anesthesiology-department'],
  ['UNC Health Perfusionist posting (2026)','https://jobs.unchealthcare.org/jobs/17876751-perfusionist-unc-medical-center'],
  ['Case Western MSA tuition (2026–27)','https://case.edu/medicine/msa-program/admissions/tuition-and-fees'],
  ['UNCG Nurse Anesthesia DNP catalog','https://catalog.uncg.edu/nursing/nursing-dnp/nursing-dnp.pdf']
];
